# Generated by Django 5.1.1 on 2024-09-10 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets_ouverts',
            name='status',
            field=models.CharField(choices=[('ouvert', 'Ouvert'), ('fermé', 'Fermé')], default='ouvert', max_length=20),
        ),
    ]
